name: Build and Deploy to Azure Cloud Run

on:
  push:
    branches: [ "master" ]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  generate-tag-version:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: v
          
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
    outputs: 
      tagVersion: "${{ steps.release.outputs.version }}"
  deploy:
    runs-on: ubuntu-latest
    needs: generate-tag-version
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v0
        with:
          #appSourcePath: ${{ github.workspace }}
          imageToBuild: jkapp.azurecr.io/app:${{ needs.generate-tag-version.outputs.tagVersion }}
          #dockerfilePath: Dockerfile
          acrName: jkapp
          acrUsername: ${{ secrets.REGISTRY_USERNAME }}
          acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppName: rest-api
          resourceGroup: testResource
          containerAppEnvironment: managedEnvironment-testResource-ad69
