name: Traffic shaping
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

env:
  PROJECT_ID: testproject-373020 # TODO: update Google Cloud project id
  GAR_LOCATION: us-east5 # TODO: update Artifact Registry location
  REPO_NAME: jkapprepo # TODO: update Cloud Run service name
  REGION: us-east5 # TODO: update Cloud Run service region
  SERVICE_NAME: website
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  get-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: 'Create new milestone'
        id: createmilestone
        uses: "WyriHaximus/github-action-create-milestone@v1"
        with:
          title: ${{ steps.semvers.outputs.patch }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.previoustag.outputs.tag }}"     
    outputs: 
      tagVersion: "${{ steps.previoustag.outputs.tag }}"
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    needs: get-tag
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # actions/checkout MUST come before auth
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/1081210593349/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'jkaccount@testproject-373020.iam.gserviceaccount.com'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
           service: ${{ env.SERVICE_NAME }}
           region: ${{ env.REGION }}
           tag_traffic: 'blue=10'
           image: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ needs.get-tag.outputs.tagVersion }}"

